/*
 * Copyright (c) 2026, AJD
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.retronpcswapper;

import lombok.Getter;

/**
 * One row of the bundled npc-mappings.json resource: the raw model and pose
 * animation IDs a named NPC had in the 2005-era cache. Generated by the
 * dev-only NpcMappingGenerator tool; deserialized with Gson at plugin startup.
 */
@Getter
public class RetroNpcMappingEntry
{
	private String name;
	private RetroNpcCategory category;
	private int[] modelIds;
	private int idleAnim = -1;
	private int walkAnim = -1;

	// No-arg constructor for Gson
	public RetroNpcMappingEntry()
	{
	}

	public RetroNpcMappingEntry(String name, RetroNpcCategory category, int[] modelIds, int idleAnim, int walkAnim)
	{
		this.name = name;
		this.category = category;
		this.modelIds = modelIds;
		this.idleAnim = idleAnim;
		this.walkAnim = walkAnim;
	}

}
